#print("Olá mundo!")
#print(10)
#print("Lucas", 23)

print("Escola de Dados da Alura!")
print("Nome: Lucas")
print("Sobrenome: Oliveira")
print('L')
print('U')
print('C')
print('A')
print('S')
print("13 Janeiro 2003")
print("Ano:", 2026)